apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Prog\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: covid-frontend
  name: covid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: covid-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Prog\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.service: covid-frontend
    spec:
      containers:
        - image: frizzer1337/covid-frontend
          name: covid-frontend
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
